#!/bin/bash

echo "debug signal"
./matt_daemon
kill -1 $(pgrep matt)
kill -2 $(pgrep matt)
kill -3 $(pgrep matt)
kill -4 $(pgrep matt)
kill -5 $(pgrep matt)
kill -6 $(pgrep matt)
kill -7 $(pgrep matt)
kill -8 $(pgrep matt)
kill -10 $(pgrep matt)
kill -11 $(pgrep matt)
kill -12 $(pgrep matt)
kill -13 $(pgrep matt)
kill -14 $(pgrep matt)
kill -15 $(pgrep matt)
kill -16 $(pgrep matt)
kill -18 $(pgrep matt)
kill -19 $(pgrep matt)
kill -21 $(pgrep matt)
kill -22 $(pgrep matt)
kill -23 $(pgrep matt)
kill -24 $(pgrep matt)
kill -25 $(pgrep matt)
kill -26 $(pgrep matt)
kill -27 $(pgrep matt)
kill -28 $(pgrep matt)
kill -29 $(pgrep matt)
kill -30 $(pgrep matt)
kill -31 $(pgrep matt)
ps -A ; ls /var/lock/matt_daemon.lock
