name: dagger
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - uses: actions/checkout@v3
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      - name: print env var
        run: |
          env
      - name: run debug
        run: |
          go run .
